### ISSUE TITLE
Wrong coq-lsp pin

### ISSUE THREAD

**Issue by jasonrute** [JetBrains-Research/coqpilot#40]
I think the right pin in the README should be:
```
opam pin add coq-lsp 0.1.8+8.19
```
(no `.0` at the end)

Reference: https://github.com/ejgallego/coq-lsp/releases

**Comment by K-dizzled** [comment]
Thank you! [Fixed](https://github.com/JetBrains-Research/coqpilot/commit/690d00c1073351cee00f39a8dfd7ab5872db19f1)
