### ISSUE TITLE
Outline is redundant

### ISSUE THREAD

**Issue by Alizter** [JetBrains-Research/coqpilot#9]
With the Coqpilot and coq-lsp extension enabled, they both show the outline of a document leading to duplicated entries. Coqpilot probably doesn't need to also report such entries.

**Comment by K-dizzled** [comment]
Hi, Ali! Could you please tell which version you are using. And whether errors are doubled in the error panel or someway visually? I manually ignore errors in code and I thought this behavior should not have happened.

**Comment by Alizter** [comment]
The version of the coqpilot extension is `1.5.1`.

Here is what the outline pane looks like:
![image](https://github.com/JetBrains-Research/coqpilot/assets/8614547/e7a55388-739a-47da-be07-e26c94751dab)

Also apparent when using `Ctrl+P` with `@` to search for things in the document:
![image](https://github.com/JetBrains-Research/coqpilot/assets/8614547/30d3bead-e0ef-49c1-bd8e-1a83cae29c57)

**Comment by Alizter** [comment]
I suppose one solution to this would be to make coqpilot a plugin for the coq-lsp extension. That way we wouldn't have to communicate with the server with two different clients. cc @ejgallego

**Comment by K-dizzled** [comment]
> I suppose one solution to this would be to make coqpilot a plugin for the coq-lsp extension. That way we wouldn't have to communicate with the server with two different clients. cc @ejgallego

Regarding this idea, here are my thoughts from our chat with Emilio:
> Regarding your idea to hook coqpilot to coq-lsp client plugin. We believe it would have been convenient, but will  lower the generallity of the code. Moreover, we are now planning on writing a benchmark framework to evaluate how different LLMs perform on generating coq. It is going to communicate with coq-lsp in a similar way as the plugin does, so we want this part to be shared across the plugin and the benchmark. It would be easier to test stuff when its not launching electron with a vscode instance etc. And I had an idea of writing a benchmark in kotlin and compiling the required part to js, so it makes things complicated to work with coq-lsp client rather than the server itself.

**Comment by ejgallego** [comment]
By the way, the concrete reason VSCode shows this is because two extensions are registering as a `documentSymbols` provider.

**Comment by K-dizzled** [comment]
> By the way, the concrete reason VSCode shows this is because two extensions are registering as a `documentSymbols` provider.

Oh, great, thanks for an insight, Emilio.

**Comment by K-dizzled** [comment]
Hey @Alizter! Fixed this and published the update.
